replicaCount: 1
image:
  repository: 10.11.252.54:5000/zebra/meta-project
  tag: 0.0.11
  pullPolicy: IfNotPresent
service:
  name: meta-project
  type: ClusterIP
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
terminationGracePeriodSeconds: 10