server:
  port: 9000
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true