replicaCount: 1
image:
  repository: gcr.io/es-devops-d/meta-project
  tag: lastest
  pullPolicy: IfNotPresent
service:
  name: meta-project
  type: ClusterIP
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
terminationGracePeriodSeconds: 10