#https://docs.spring.io/spring-metrics/docs/current/public/prometheus
#https://www.weave.works/docs/cloud/latest/tasks/monitor/configuration-k8s/

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: meta-project
  labels:
    app: meta-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-project
  template:
    metadata:
      labels:
        app: meta-project
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: meta-project
        image: gcr.io/es-devops-d/mygroup/meta-project:latest
        ports:
          - containerPort: 9001
---
kind: Service
apiVersion: v1
metadata:
  name: meta-project-svc
spec:
  selector:
    app: meta-project
  ports:
    - name: endpoints
      protocol: TCP
      port: 9000
    - name: prometheus
      protocol: TCP
      port: 9001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: meta-project.dev.zebra.engineering
      http:
        paths:
          - path: /
            backend:
              serviceName: meta-project-svc
              servicePort: 9000
          - path: /external
            backend:
              serviceName: meta-project-svc
              servicePort: 9001