apiVersion: v1
kind: Service
metadata:
  name: {{ template "meta-project.fullname" . }}
  labels:
    app: {{ template "meta-project.name" . }}
    chart: {{ template "meta-project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: endpoints
      protocol: TCP
      port: 9000
    - name: prometheus
      protocol: TCP
      port: 9001
  selector:
    app: {{ template "meta-project.name" . }}
    release: {{ .Release.Name }}
